server:
  port: 8080

spring:
  application:
    name: ebanking-transactions-service
  kafka:
    bootstrap-servers: localhost:9092
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://localhost:9999/realms/example

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    org.springframework.security: INFO

app:
  security:
    dev-jwt-secret: dev-secret-please-change-32bytes-minimum!!!!

