version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    environment:
      MAVEN_OPTS: -Xmx1024m
    steps:
      - checkout

      # Install JDK 21 (Temurin)
      - run:
          name: Install Temurin JDK 21
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gpg apt-transport-https
            wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo gpg --dearmor -o /usr/share/keyrings/adoptium.gpg
            echo "deb [signed-by=/usr/share/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb jammy main" | sudo tee /etc/apt/sources.list.d/adoptium.list
            sudo apt-get update
            sudo apt-get install -y temurin-21-jdk
            java -version

      # Make sure the wrapper is executable
      - run:
          name: Make mvnw executable
          command: chmod +x mvnw

      # Cache Maven
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-
      - run:
          name: Build & Test (unit + integration)
          command: |
            ./mvnw -B -e -DskipITs=false verify
            # if want to exclude certain IT:
            # ./mvnw -B -e -Dtest=\!KafkaFlowIT verify

      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository

      - run:
          name: Build Docker image
          command: |
            docker --version
            docker build -t ebanking-transactions-service:ci .

workflows:
  build_and_test:
    jobs:
      - build-and-test
